-- PASO 1: Copia TODO este texto.
-- PASO 2: Ve a Supabase -> SQL Editor -> New Query.
-- PASO 3: Pega y corre esto (Run).

-- Esto permite que la PC le diga a Supabase qué ID usar (para mantenerlos iguales).
ALTER TABLE products ALTER COLUMN id SET GENERATED BY DEFAULT;

-- Confirmación visual
SELECT '✅ ARREGLADO: Ahora Supabase acepta IDs manuales.' as status;
